### ISSUE TITLE
The results of FTE are weird.

### ISSUE THREAD

**Issue by DenDen047** [African-Robotics-Unit/AcinoSet#7]

**Comment by DJoska** [comment]
Naoya, I'm looking at the FTE results you uploaded on the dropbox and it looks like you have reconstructed every frame from the beginning to the end instead of choosing a good window of frames where the cheetah is centred - are these the issues that you're referring to? Or does the issue persist even when you choose, say, the best 100 frames to reconstruct?

**Comment by rickyjericevich** [comment]
The issue persists even if you use the best 100 frames

**Comment by rickyjericevich** [comment]
The problem was that the output for glob calls was left unsorted in the code (see [this](https://bugs.python.org/issue33275#msg315254). I pushed the fix https://github.com/African-Robotics-Unit/AcinoSet/commit/a9747a23d37b6f1fb30f058860470101074a1503
